FROM centos:7

LABEL maintainer="chenleji <chenleji@gmail.com>"

ENV FLANNEL_ARCH=amd64

RUN yum install -y ebtables iptables
COPY dist/flanneld-$FLANNEL_ARCH /opt/bin/flanneld
COPY dist/mk-docker-opts.sh /opt/bin/
COPY dist/yonghui /opt/bin/

ENTRYPOINT ["/opt/bin/flanneld"]

